apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres-fiap-lanches.fullname" . }}
  labels:
    {{- include "postgres-fiap-lanches.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      nodePort: 32001
  selector:
    {{- include "postgres-fiap-lanches.selectorLabels" . | nindent 4 }}
